---
kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
  - go mod download
  - go test

- name: metadata
  image: alpine:latest
  commands:
  - wget -O - http://169.254.169.254/2016-09-02/meta-data/hostname
